<?php
////////////////////////////////////////////
//////////////// RECORDINGS ////////////////
////////////////////////////////////////////

// add record
if ("$ac" === "recordadd") {

	$q = "INSERT INTO `recordings` (`userId`, `startDate`, `endDate`, `flossed`, `rinsed`, `coinsGenerated`) VALUES ('$userId', '$startDate', '$endDate', '$flossed', '$rinsed', '$coinsGenerated')";
	$qq = mysqli_query($dblink, $q);
	$t = mysqli_insert_id($dblink);
	$err = mysqli_error($dblink);
	if ($t > 0) { echo "OK|RECORD ADD OK|$t"; } else { echo "ERR|$err"; }

}

// del record
if ("$ac" === "recorddel") {

	if ($recordid < 1) { echo "ERR|NO RECORD ID"; } else {
	$q = "DELETE FROM `recordings` WHERE `id` = '$recordid'";
	$qq = mysqli_query($dblink, $q);
	$err = mysqli_error($dblink);
	
	if ("$err" === "") {
	
		if (mysqli_affected_rows($dblink) > 0) {
			echo "OK|RECORD DEL OK"; 
			} else {
			echo "ERR|RECORD NOT EXIST"; 	
		} 
	
	} else { echo "ERR|$err"; }
	}
}

// edit record
if ("$ac" === "recordedit") {

	if ($recordid < 1) { echo "ERR|NO RECORD ID"; } else {
	$q = "UPDATE `recordings` SET `userId` = '$userId', `startDate` = '$startDate', `endDate` = '$endDate', `flossed` = '$flossed', `rinsed` = '$rinsed', `coinsGenerated` = '$coinsGenerated' WHERE `id` = '$recordid'";
	$qq = mysqli_query($dblink, $q);
	$err = mysqli_error($dblink);
	
	if ("$err" === "") {
	
		if (mysqli_affected_rows($dblink) > 0) {
			echo "OK|RECORD UPDATE OK"; 
			} else {
			echo "ERR|RECORD NOT EXIST"; 	
		} 
	
	} else { echo "ERR|$err"; }
	

	}

}

// view record
if ("$ac" === "recordview") {

	if ($recordid < 1) { echo "ERR|NO RECORD ID"; } else {
	$q = "SELECT * FROM `recordings` WHERE `id` = '$recordid'";
	$qq = mysqli_query($dblink, $q);
	$qqq = mysqli_fetch_array($qq);
	$err = mysqli_error($dblink);
	
	if ("$err" === "") {
	
	echo "OK|userId:$qqq[userId]|startDate:$qqq[startDate]|endDate:$qqq[endDate]|flossed:$qqq[flossed]|rinsed:$qqq[rinsed]|coinsGenerated:$qqq[coinsGenerated]";
		 
	
	} else { echo "ERR|$err"; }
	

	}

}

// view coins generated by user
if ("$ac" === "coinsbyuser") {

	if ($userid < 1) { echo "ERR|NO USER ID"; } else {
	$q = "SELECT sum(`coinsGenerated`) as coins FROM `recordings` WHERE `userId` = '$userid'";
	$qq = mysqli_query($dblink, $q);
	$qqq = mysqli_fetch_array($qq);
	$err = mysqli_error($dblink);
	
	if ("$err" === "") {
	
	echo "OK|userId:$qqq[userId]|coins:$qqq[coins]";
	
	} else { echo "ERR|$err"; }
	}
}


?>